### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by agcopenhaver**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
@sodre got any changes here? I removed the conda_forge_meta.yaml which had the pinnings in it.

**Comment by sodre** [comment]
@agcopenhaver, I think we need to add at least the max-min pins back.

**Pull request closed without merging**
